#!/bin/sh
ssh-keygen -A >/dev/null 2>&1       # This will generate host keys if they don't already exist
if test -f /etc/default/ssh; then
    . /etc/default/ssh              # Set up systemwide defaults if they're specified...
fi
exec /usr/sbin/sshd -D $SSHD_OPTS
