#!/bin/sh

# Handle shutdowns...the daemons connman launches are subject to
# dismissal at the time we get ran.
SVC_LIST="wpa_supplicant hostapd ofonod"
for SVC in $SVC_LIST; do
    killall -9 $SVC > /dev/null
done

