#!/bin/sh

# Check to see if we've got any special rules other than the stuff
# below for NFS roots to handle and bring them in...
[ -r ./config ] && . ./config

# Check to see if we're mounted as an NFS root.  (Little different 
# set of operating rules if we are...)
set -e
nfsroot=0
exec 9<&0 < /proc/mounts
while read dev mtpt fstype rest; do
	if test $mtpt = "/" ; then
		case $fstype in
		    nfs | nfs4)
			nfsroot=1
			break
			;;
		    *)
			;;
		esac
	fi
done

# Now setup and launch...
EXTRA_PARAM=""
if [ $nfsroot -eq 1 ]; then
    NET_DEVS=`cat /proc/net/dev | sed -ne 's/^\([a-zA-Z0-9 ]*\):.*$/\1/p'`
    NET_ADDR=`cat /proc/cmdline | sed -ne 's/^.*ip=\([^ :]*\).*$/\1/p'`

    if [ ! -z "$NET_ADDR" ]; then
	if [ "$NET_ADDR" = dhcp ]; then
	    ethn=`ifconfig | grep "^eth" | sed -e "s/\(eth[0-9]\)\(.*\)/\1/"`
	    if [ ! -z "$ethn" ]; then
		EXTRA_PARAM="-I $ethn"
	    fi
	else
	    for i in $NET_DEVS; do
		ADDR=`ifconfig $i | sed 's/addr://g' | sed -ne 's/^.*inet \([0-9.]*\) .*$/\1/p'`
		if [ "$NET_ADDR" = "$ADDR" ]; then
		    EXTRA_PARAM="-I $i"
		    break
		fi
	    done
	fi
    fi
fi
exec connmand --nodaemon $WIFI_PARAM $EXTRA_PARAM 2>&1



