#!/bin/sh

# Check to see if we've got any special rules other than the stuff
# below for NFS roots to handle and bring them in...  This lives in
# two places.  One's in the /etc/defaults place, the other lives
# in here with this run as a provisioned, which WiFi management
# engine are we running with...
[ -r /etc/default/connman ] && . /etc/default/connman
[ -r ./config ] && . ./config

# Handle a few potential problems with this runlevel.  connman controls
# things like wpa_supplicant, ofono, etc., so we don't want runit
# services files for the others right now.  They cause weird problems
# with scans, etc.
SVC_LIST="wpa_supplicant iwd hostapd ofono"
for SVC in $SVC_LIST; do
    # Check to make sure the service even is there...
    if [ ! -e /etc/sv/$SVC ]; then
        # Presume it is, now we need to check to see if it's started or not- if so, NUKE IT.
        svc_running $SVC 2>&1 > /dev/null
        if [ $? -eq 0 ] ; then
            # This would be up and running.  Shut it off.
            sv exit $SVC
            sv force-stop $SVC

            # Now, make sure we tag this one as DOWN for now.
            if [ ! -e /etc/sv/$SVC/down ]; then
                touch /etc/sv/$SVC/down
            fi
        fi
    fi
done

# Check to see if we're mounted as an NFS root.  (A little different
# set of operating rules if we are...)  We're going to get clever- the
# prior way was...broken...on the case of running against the VisionFive2
# RISC-V target, so, we're going to AWK our way through this.
nfsroot=$(cat /proc/mounts|awk 'BEGIN{nfsroot=0} /nfs/{if($2 == "/") {nfsroot=1}} END{print nfsroot}')

# Now setup and launch...
EXTRA_PARAM=""
if [ $nfsroot -eq 1 ]; then
    NET_DEVS=`cat /proc/net/dev | sed -ne 's/^\([a-zA-Z0-9 ]*\):.*$/\1/p'`
    NET_ADDR=`cat /proc/cmdline | sed -ne 's/^.*ip=\([^ :]*\).*$/\1/p'`

    if [ ! -z "$NET_ADDR" ]; then
        if [ "$NET_ADDR" = dhcp ]; then
            ethn=`ifconfig | grep "^eth" | sed -e "s/\(eth[0-9]\)\(.*\)/\1/"`
            if [ ! -z "$ethn" ]; then
            EXTRA_PARAM="-I $ethn"
            fi
        else
            for i in $NET_DEVS; do
            ADDR=`ifconfig $i | sed 's/addr://g' | sed -ne 's/^.*inet \([0-9.]*\) .*$/\1/p'`
            if [ "$NET_ADDR" = "$ADDR" ]; then
                EXTRA_PARAM="-I $i"
                break
            fi
            done
        fi
    fi
fi
exec connmand --nodaemon $CONFIG_PARAM $WIFI_PARAM $EXTRA_PARAM 2>&1



