#!/bin/sh

# If the "daemon" that set the clock exits, save off the system clock
# to the HW one...
[ ! -x /sbin/hwclock ] && exit 0

. /etc/runit/functions

[ -f /etc/default/hwclock ] && . /etc/default/hwclock

if [ "$HWCLOCKACCESS" != no ] ; then
    # Have a HW RTC of some sort.  Operate on the thing accordingly.
    # (This way GPS/NTP/PTP will set the system clock precisely and then
    #  we start up with the roughly correct time at boot.)
	hwclock $tz --systohc
	if [ "$VERBOSE" != no ] ; then
		msg "Hardware Clock updated to `date`."
	fi
fi

