#!/bin/sh

# Pause so it leaves it ready to trigger on exit, letting us hook saving
# of the system clock to the RTC on restart or down for this, "service,"
# neatly handling the save under all contexts it'd need to be done.
exec pause

